# Generated by Django 3.1.2 on 2020-11-03 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='_type',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='path',
        ),
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(default=None, upload_to='video/%y'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 13, 59, 38, 231721, tzinfo=utc)),
        ),
    ]
