# Generated by Django 3.1.2 on 2020-11-03 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20201103_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='name',
            new_name='caption',
        ),
        migrations.AlterField(
            model_name='upload',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 14, 10, 40, 854149, tzinfo=utc)),
        ),
    ]
