# Generated by Django 3.1.2 on 2020-11-03 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20201103_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='caption',
            field=models.CharField(default='File', max_length=200),
        ),
        migrations.AlterField(
            model_name='upload',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 14, 20, 21, 949471, tzinfo=utc)),
        ),
    ]
