# Generated by Django 3.1.2 on 2020-10-29 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default=None)),
                ('url_details', models.TextField(default=None)),
                ('url_thumb', models.TextField(default='default.jpg')),
                ('date_inserted', models.DateField(default=datetime.datetime(2020, 10, 29, 16, 9, 31, 818679, tzinfo=utc))),
                ('date_modified', models.DateField(default=datetime.datetime(2020, 10, 29, 16, 9, 31, 818679, tzinfo=utc))),
            ],
        ),
    ]
