# Generated by Django 3.1.2 on 2020-10-29 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='url_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urls',
            name='date_inserted',
            field=models.DateField(default=datetime.datetime(2020, 10, 29, 23, 26, 11, 956785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='urls',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 10, 29, 23, 26, 11, 957288, tzinfo=utc)),
        ),
    ]
